version: '3.7'
services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - app-network
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb
    depends_on:
      - mongodb
    restart: on-failure
    networks:
      - app-network
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: uop-findajob-server
    container_name: uop-findajob-node-server
    command: npm run prod
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3001:3001'
    depends_on:
      - mongodb
      - mongo-seed
    env_file: ./server/.env
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - app-network
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: uop-findajob-client
    container_name: uop-findajob-node-client
    ports:
      - '80:80'
    depends_on:
      - server
    environment:
      - NODE_ENV=production
    networks:
      - app-network
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
      - mongo-seed
    networks:
      - app-network
    ports:
      - 8084:8084
    restart: unless-stopped
networks:
  app-network:
    driver: bridge
